from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DEFAULT_MANUSCRIPT = ROOT / "paper" / "main.tex"
DEFAULT_OUT = ROOT / "paper" / "submission_package" / "quality_audit_report.md"


DEFENSIVE_PHRASES = [
    "does not claim",
    "do not claim",
    "not a claim",
    "should be read as",
    "we only",
    "merely",
    "black box",
    "black-box",
]

AI_MARKERS = [
    "chatgpt",
    "codex",
    "large language model",
    "ai-generated",
    "generated by ai",
]

LONG_WORD_THRESHOLD = 52


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def line_number(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def strip_tex(text: str) -> str:
    text = re.sub(r"%.*", "", text)
    text = re.sub(r"\\cite[t|p]?\{[^{}]*\}", "", text)
    text = re.sub(r"\\[a-zA-Z]+\*?(?:\[[^\]]*\])?(?:\{([^{}]*)\})?", r"\1", text)
    text = re.sub(r"[{}$]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def extract_environment(text: str, name: str) -> str:
    match = re.search(
        rf"\\begin\{{{re.escape(name)}\}}(.*?)\\end\{{{re.escape(name)}\}}",
        text,
        flags=re.DOTALL,
    )
    return match.group(1).strip() if match else ""


def extract_keywords(text: str) -> list[str]:
    match = re.search(
        r"\\textbf\{Keywords:\}(.*?)(?:\n\s*\n|\\section\{)",
        text,
        flags=re.DOTALL | re.IGNORECASE,
    )
    if not match:
        return []
    raw = strip_tex(match.group(1)).rstrip(".")
    return [item.strip() for item in raw.split(",") if item.strip()]


def strip_ai_declaration(text: str) -> tuple[str, bool]:
    pattern = (
        r"\\section\*\{Declaration of Generative AI and AI-Assisted Technologies\}"
        r".*?(?=\\section\*|\\bibliographystyle|\\bibliography|\\end\{document\})"
    )
    cleaned, count = re.subn(pattern, "", text, flags=re.DOTALL | re.IGNORECASE)
    return cleaned, bool(count)


def word_count(text: str) -> int:
    return len(re.findall(r"[A-Za-z]+(?:[-'][A-Za-z]+)?", strip_tex(text)))


def long_sentences(text: str, threshold: int) -> list[tuple[int, int, str]]:
    plain = strip_tex(text)
    pieces = re.split(r"(?<=[.!?])\s+", plain)
    findings = []
    for idx, sentence in enumerate(pieces, start=1):
        words = word_count(sentence)
        if words > threshold:
            findings.append((idx, words, sentence[:220]))
    return findings


def find_phrase_lines(text: str, phrases: list[str]) -> list[tuple[str, int, str]]:
    findings = []
    lowered = text.lower()
    for phrase in phrases:
        for match in re.finditer(re.escape(phrase.lower()), lowered):
            start = max(0, match.start() - 70)
            end = min(len(text), match.end() + 100)
            context = " ".join(text[start:end].split())
            findings.append((phrase, line_number(text, match.start()), context))
    return findings


def parse_includegraphics(text: str) -> list[tuple[int, str]]:
    out = []
    for match in re.finditer(r"\\includegraphics(?:\[[^\]]*\])?\{([^{}]+)\}", text):
        out.append((line_number(text, match.start()), match.group(1)))
    return out


def parse_resizeboxes(text: str) -> list[tuple[int, str]]:
    out = []
    for match in re.finditer(r"\\resizebox\{[^{}]+\}\{[^{}]+\}\{\\input\{([^{}]+)\}\}", text):
        out.append((line_number(text, match.start()), match.group(1)))
    return out


def audit(manuscript: Path) -> tuple[list[str], list[str], list[str]]:
    text = read_text(manuscript)
    errors: list[str] = []
    warnings: list[str] = []
    notes: list[str] = []

    abstract = extract_environment(text, "abstract")
    abstract_words = word_count(abstract)
    if not abstract:
        errors.append("No abstract environment found.")
    elif abstract_words < 120 or abstract_words > 250:
        warnings.append(f"Abstract length is {abstract_words} words; target 150-220 for GEB/JET style.")
    else:
        notes.append(f"Abstract length: {abstract_words} words.")

    keywords = extract_keywords(text)
    if not keywords:
        errors.append("No keyword line found.")
    else:
        notes.append(f"Keywords: {len(keywords)} ({', '.join(keywords)}).")
        if len(keywords) > 6:
            warnings.append(f"Keyword count is {len(keywords)}; consider five or six concise terms.")
        long_keywords = [kw for kw in keywords if len(kw.split()) > 3]
        if long_keywords:
            warnings.append("Long keyword(s): " + ", ".join(long_keywords))

    defensive = find_phrase_lines(text, DEFENSIVE_PHRASES)
    if defensive:
        for phrase, line, context in defensive:
            warnings.append(f"Defensive phrase `{phrase}` at line {line}: {context}")
    else:
        notes.append("No repeated high-risk defensive phrases from the local list.")

    text_without_ai_declaration, has_ai_declaration = strip_ai_declaration(text)
    ai_markers = find_phrase_lines(text_without_ai_declaration, AI_MARKERS)
    if ai_markers:
        for phrase, line, context in ai_markers:
            warnings.append(f"Submission-facing AI marker `{phrase}` at line {line}: {context}")
    else:
        if has_ai_declaration:
            notes.append("No undeclared AI-tool markers outside the manuscript AI declaration.")
        else:
            notes.append("No explicit AI-tool markers in the manuscript source.")

    title_match = re.search(r"\\title\{([^{}]+)\}", text)
    if title_match:
        title_words = word_count(title_match.group(1))
        if title_words > 18:
            warnings.append(f"Title is {title_words} words; consider shortening if the target journal prefers concise titles.")
        else:
            notes.append(f"Title length: {title_words} words.")

    include_dir = manuscript.parent
    graphics = parse_includegraphics(text)
    if not graphics:
        warnings.append("No includegraphics command found.")
    for line, graphic in graphics:
        path = include_dir / graphic
        if not path.exists():
            errors.append(f"Figure path missing at line {line}: {graphic}")
        elif path.suffix.lower() not in {".pdf", ".svg", ".eps"}:
            warnings.append(f"Main-text figure is not vector at line {line}: {graphic}")
        else:
            notes.append(f"Vector figure at line {line}: {graphic}")

    resizeboxes = parse_resizeboxes(text)
    if resizeboxes:
        notes.append(f"Main text uses {len(resizeboxes)} resizebox-wrapped table(s).")
        for line, table in resizeboxes:
            warnings.append(f"Review wide table layout at line {line}: {table}")

    combined_sections = "\n".join([abstract, text.split(r"\section{Introduction}", 1)[-1][:8000]])
    for idx, words, preview in long_sentences(combined_sections, LONG_WORD_THRESHOLD)[:8]:
        warnings.append(f"Long sentence candidate {idx}: {words} words. Preview: {preview}")

    return errors, warnings, notes


def write_report(path: Path, manuscript: Path, errors: list[str], warnings: list[str], notes: list[str]) -> None:
    status = "PASS" if not errors else "FAIL"
    if warnings and status == "PASS":
        status = "WARN"

    lines = [
        "# Manuscript Quality Audit",
        "",
        f"Manuscript: `{manuscript.relative_to(ROOT).as_posix()}`",
        f"Status: **{status}**",
        "",
        "This audit checks common submission-facing polish risks: abstract length, keyword discipline, "
        "defensive phrasing, AI-tool residue, vector figures, wide tables, and unusually long sentences. "
        "Warnings are editorial prompts, not automatic reasons to rewrite the paper.",
        "",
        "## Errors",
        "",
    ]
    lines.extend([f"- {item}" for item in errors] or ["- None."])
    lines.extend(["", "## Warnings", ""])
    lines.extend([f"- {item}" for item in warnings] or ["- None."])
    lines.extend(["", "## Notes", ""])
    lines.extend([f"- {item}" for item in notes] or ["- None."])
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit submission-facing manuscript polish.")
    parser.add_argument("--manuscript", type=Path, default=DEFAULT_MANUSCRIPT)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--strict", action="store_true", help="Return nonzero on warnings as well as errors.")
    args = parser.parse_args()

    errors, warnings, notes = audit(args.manuscript)
    write_report(args.out, args.manuscript, errors, warnings, notes)
    print(f"Wrote {args.out}")
    if errors or (args.strict and warnings):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
